title: Arrow Analysis
#-------------------------
name: Λrrow Analysis
#-------------------------
description: Pre-, post-condition, and invariant checks for your Kotlin code
#-------------------------
author: The Λrrow Authors
keywords: functional-programming, kotlin-library, static-analysis, contracts
#-------------------------
url: https://arrow-kt.io/docs/analysis
#-------------------------
arrow_url: https://arrow-kt.io
#-------------------------
github_repo: https://github.com/arrow-kt/arrow-analysis
#-------------------------
twitter_handle: "@arrow_kt"
#-------------------------
slack_kotlin_channel: "https://slack.kotlinlang.org"
slack_arrow_channel: "https://kotlinlang.slack.com/archives/C5UPMM0A0"
#-------------------------
markdown: kramdown
sass:
    style: compressed
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'build', 'build.gradle.kts', 'gradle.properties']
#-------------------------
defaults:
  - scope:
      path: "apidocs"
      type: "pages"
    values:
      layout: "docs-analysis"
