name: Testing publish documentation

on:
  push:
    branches: [import-docs]

jobs:
  publish_documentation:
    needs: build
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID_FOR_TESTING }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      JEKYLL_ENV: production
      S3_BUCKET: ${{ secrets.S3_BUCKET_FOR_TESTING }}

    steps:
      - uses: actions/checkout@v3.0.0

      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '15'
          cache: 'gradle'

      - name: Prepare environment
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --gemfile docs/Gemfile

      - name: Create API Doc and validate
        run: ./gradlew buildDoc

      - name: Generate site
        run: bundle exec jekyll build -b docs/analysis -s docs/docs -d docs/build/_site

      - name: Upload site to S3 bucket
        run: aws s3 sync --delete docs/build/_site s3://$S3_BUCKET/docs/analysis

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/docs/analysis"