name: Build Artifacts for PR

on: pull_request

env:
  JAVA_OPTS: -Xms512m -Xmx1024m
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"


jobs:
  pull_request:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        kotlin: ['1.6.0', '1.6.10']
        jvm_target: ['1.8', '11', '15']

    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Build and test with Gradle
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: -PkotlinVersion=${{ matrix.kotlin }} -PjvmTargetVersion=${{ matrix.jvm_target }} build --scan --stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

      - name: Bundle SARIF report
        run: mkdir sarif && find . -name '*.sarif' | xargs -I{} cp "{}" ./sarif/

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1.1.5
        continue-on-error: true
        with:
        # Path to SARIF file relative to the root of the repository
          sarif_file: sarif
